### ISSUE TITLE
Automated merge requests fail due to linting issues

### ISSUE THREAD

**Issue by marianne013** [conda-forge/apache-libcloud-feedstock#33]
### Comment:

Hi All, 

The DIRAC project (https://dirac.readthedocs.io/en/latest/index.html) takes a number of packages from conda-forge, among them libcloud. 
However it looks like the automated pull requests fail due to a linting issue and I am wondering if there is any plan to maintain apache-libcloud in conda-forge ? (@chrisburr) 

Daniela

**Comment by chrisburr** [comment]
Fixed in https://github.com/conda-forge/apache-libcloud-feedstock/pull/32
